export default {
    options: [
        {
            id: "ing",
            label: "Ending in ING",
        },
        {
            id: "ly",
            label: "Ending in LY",
        },
        {
            id: "ed",
            label: "Ending in ED",
        },
        {
            id: "past-tense",
            label: "Past Tense",
        },
        {
            id: "plural",
            label: "Plural",
        },
    ],
    types: [
        {
            id: "noun",
            label: "Noun",
            description: "A noun is the name of a person, place, thing, or idea.",
            example: "man, McDonalds, house, happiness",
        },
        {
            id: "pronoun",
            label: "Pronoun",
            description: "A pronoun is a word used in place of a noun.",
            example: "She, we, they, it",
        },
        {
            id: "interjection",
            label: "Interjection",
            description: "An interjection is a word used to express emotion.",
            example: "Oh!, Wow!, Oops!",
        },
        {
            id: "adjective",
            label: "Adjective",
            description: "An adjective modifies or describes a noun or pronoun.",
            example: "pretty, old, blue, smart",
        },
        {
            id: "adverb",
            label: "Adverb",
            description: "Usually ending in “ly”, an adverb modifies or describes a verb, an adjective, or another adverb.",
            example: "gently, extremely, carefully, well",
        },
        {
            id: "body-part",
            label: "Part of the Body",
            description: "Something attached to the human body.",
            example: "knee, teeth, butt, brain",
        },
        {
            id: "verb",
            label: "Verb",
            description: "A verb expresses action or being.",
            example: "jump, is, write, become",
        },
        {
            id: "female-relative",
            label: "Female Relative",
            description: "A female member of your family.",
            example: "aunt may, mom, susie, grandma",
        },
        {
            id: "male-relative",
            label: "Male Relative",
            description: "A male member of your family.",
            example: "uncle bob, dad, johnny, grandpa",
        },
        {
            id: "relative",
            label: "Family Relative",
            description: "A member of your family.",
            example: "mom, dad, jessica, grandpa",
        },
        {
            id: "number",
            label: "Number",
            description: "Any number (not a negative number).",
            example: "1, 3.14159, 100, 1,000,000,000",
        },
        {
            id: "food",
            label: "Food",
            description: "Anything that is considered edible.",
            example: "lasanga, bread, egg yolk, deer",
        },
        {
            id: "instrument",
            label: "Instrument",
            description: "Something that is used to create music.",
            example: "bass, drums, triangle, cowbell",
        },
        {
            id: "song",
            label: "Song Title",
            description: "A title of a song.",
            example: "Welcome to the Jungle, What I Got, Mary Had a Little Lamb, Holy Wars",
        },
        {
            id: "time",
            label: "Time of Day",
            description: "Any time of day.",
            example: "noon, 3:30pm, dinner time, midnight",
        },
        {
            id: "thing",
            label: "Thing",
            description: "A material object or idea",
            example: "the blob, paint, boogeyman, snow",
        },
        {
            id: "taste",
            label: "Taste",
            description: "Something you can taste.",
            example: "snot, chocolate, bbq chicken, carrot",
        },
        {
            id: "holiday",
            label: "Holiday",
            description: "Any celebrated or non-celebrated holiday",
            example: "easter, thanksgiving, christmas, pi day",
        },
        {
            id: "color",
            label: "Color",
            description: "Any color.",
            example: "red, sky blue, white, gray",
        },
        {
            id: "made-up-word",
            label: "Made Up Word",
            description: "A word that is not in the dictionary.",
            example: "Habble, whark, mobify, bloatware",
        },
        {
            id: "silly-word",
            label: "A Silly Word",
            description: "A word that sounds silly",
            example: "bubbles, squishy, snarf, booger",
        },
        {
            id: "drink",
            label: "Drinkable Liquid",
            description: "Anything that is considered drinkable.",
            example: "milk, pee, soda, iced tea",
        },
        {
            id: "liquid",
            label: "Liquid",
            description: "Any type liquid.",
            example: "gas, soda, toilet water, milk",
        },
        {
            id: "place",
            label: "Place",
            description: "A physical place or location.",
            example: "home, work, China, space",
        },
        {
            id: "person",
            label: "Person",
            description: "A persons name or occupation.",
            example: "Jim, janitor, Sally, cop",
        },
        {
            id: "emotion",
            label: "Emotion",
            description: "A feeling or state of mind.",
            example: "sad, happy, hopeful, overjoyed",
        },
        {
            id: "animal",
            label: "Animal",
            description: "Any animal (invertebrates and vertebrates).",
            example: "whale, snake, slug, pigeon",
        },
        {
            id: "sex-position",
            label: "Sex Position",
            description: "A body position during sex.",
            example: "doggystyle, reverse cowgirl, dirty trombone, double fisting",
        },
        {
            id: "word-for-sex",
            label: "A Word for Sex",
            description: "An alternate word for sex.",
            example: "fuck, bang, smash, pound",
        },
        {
            id: "word-for-breasts",
            label: "A Word for Breasts",
            description: "An alternate word for breasts.",
            example: "tits, boobies, rack, honkers",
        },
        {
            id: "word-for-semen",
            label: "A Word for Semen",
            description: "An alternate word for semen.",
            example: "cum, jizz, splooge, white stuff",
        },
        {
            id: "female-reproductive-organ",
            label: "A Name for a Female Reproductive Organ",
            description: "Another word to call the vagina.",
            example: "pussy, box, cunt, snatch",
        },
        {
            id: "male-reproductive-organ",
            label: "A Name for a Male Reproductive Organ",
            description: "Another word to call the penis.",
            example: "dick, cock, schlong, monster",
        },
        {
            id: "race",
            label: "Ethnicity/Race",
            description: "The heritage of a person or a color of skin.",
            example: "black, asian, indian, white",
        },
        {
            id: "cuss-word",
            label: "Cuss Word",
            description: "A word to curse at something or someone.",
            example: "bitch, asshole, fuck, dickhead",
        },
        {
            id: "friend",
            label: "A Friend‘s Name",
            description: "A living being who is your friend.",
            example: "my dog, Dann, cable guy, neighbor",
        },
        {
            id: "person-in-room",
            label: "Someone in the Room",
            description: "A living being who is in the room right now.",
            example: "my dog, John, mom, neighbor",
        },
    ]
}